### ISSUE TITLE
Tardis key destroyed when used on landing pad with "Emergency Exit" upgrade

### ISSUE THREAD

**Issue by ghost** [ThreeTAG/TriadTech#1]
Forge 47.3.0-1.20.1

My Tardis key was destroyed when used on landing pad while testing, pretty sure it's because of the "Emergency Exit" upgrade.
Using the latest Modrinth version with the new Tardis Refined update, but this happened on the update before too...

**Comment by ghost** [comment]
If anyone finds this, I have made my own mod to fix this exact issue and add more features, Tardis Expanded!
Currently adds the same stuff as this mod, but I am actively working on more features!
You can grab it here: [https://modrinth.com/mod/tardis-expanded](https://modrinth.com/mod/tardis-expanded)

**Comment by Jeryn99** [comment]
> If anyone finds this, I have made my own mod to fix this exact issue and add more features, Tardis Expanded! Currently adds the same stuff as this mod, but I am actively working on more features! You can grab it here: https://modrinth.com/mod/tardis-expanded



You created a addon mod for a addon mod, that's a addon mod for a mod?


I do hope you got permission to use their idea in your mod

**Comment by Lucraft** [comment]
> > If anyone finds this, I have made my own mod to fix this exact issue and add more features, Tardis Expanded! Currently adds the same stuff as this mod, but I am actively working on more features! You can grab it here: https://modrinth.com/mod/tardis-expanded
> 
> You created a addon mod for a addon mod, that's a addon mod for a mod?
> 
> I do hope you got permission to use their idea in your mod

He, infact, did not

**Comment by Lucraft** [comment]
I do still plan to fix this, I just didnt have time yet
